//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductFiles
    {
        public int FileID { get; set; }
        public int ProductID { get; set; }
        public string FileURL { get; set; }
        public string FileType { get; set; }
    
        public virtual Products Products { get; set; }
    }
}
